version: '3.4'
networks:
  supermercado-network:
    driver: bridge
services:
  listasupermercado.api:
    image: listasupermercadoapi:latest
    build:
      context: .
      dockerfile: src/ListaSupermercado.API/Docker/api.dockerfile
      network: supermercado-network
  listasupermercado.db:
    image: listasupermercadodb:latest
    container_name: listasupermercadodb
    ports:
      - "1433:1433"
    build:
      context: .
      dockerfile: src/ListaSupermercado.API/Docker/db.dockerfile
      network: supermercado-network