// <auto-generated />
using System;
using Listasupermercado.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Listasupermercado.Infrastructure.Migrations
{
    [DbContext(typeof(BaseContext))]
    [Migration("20200628195933_itemcarrinho")]
    partial class itemcarrinho
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ListaSupermercado.Domain.Entity.CarrinhoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemCarrinhoEntityCarrinhoId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemCarrinhoEntityProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCarrinhoEntityCarrinhoId", "ItemCarrinhoEntityProdutoId");

                    b.ToTable("Carrinhos");
                });

            modelBuilder.Entity("ListaSupermercado.Domain.Entity.ItemCarrinhoEntity", b =>
                {
                    b.Property<int>("CarrinhoId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("CarrinhoId", "ProdutoId");

                    b.ToTable("ItemCarrinho");
                });

            modelBuilder.Entity("ListaSupermercado.Domain.Entity.ProdutoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ItemCarrinhoEntityCarrinhoId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemCarrinhoEntityProdutoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ItemCarrinhoEntityCarrinhoId", "ItemCarrinhoEntityProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("ListaSupermercado.Domain.Entity.CarrinhoEntity", b =>
                {
                    b.HasOne("ListaSupermercado.Domain.Entity.ItemCarrinhoEntity", null)
                        .WithMany("Carrinhos")
                        .HasForeignKey("ItemCarrinhoEntityCarrinhoId", "ItemCarrinhoEntityProdutoId");
                });

            modelBuilder.Entity("ListaSupermercado.Domain.Entity.ProdutoEntity", b =>
                {
                    b.HasOne("ListaSupermercado.Domain.Entity.ItemCarrinhoEntity", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ItemCarrinhoEntityCarrinhoId", "ItemCarrinhoEntityProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
